import {
Dna,
Droplets,
Activity,
HeartPulse,
Microscope,
Brain,
Smile,
ShieldAlert,
Ear,
Thermometer,
Syringe,
Cross,
Scan,
Baby,
Stethoscope,
Eye,
Bone,
Pill,
type LucideIcon,
} from "lucide-react";

export interface Department {
  id: string;
  slug: string;
  name: string;
  icon: LucideIcon;
  desc: string;
  fullDesc: string;
  category: "speciality" | "diagnostic" | "emergency" | "support" | string;
  image: string;
  procedures: string[];
  facilities: string[];
}

export const departments: Department[] = [
  {
    id: "anaesthesia",
    slug: "anaesthesia",
    name: "Anaesthesia",
    icon: Dna,
    desc: "Anaesthesia department",
    fullDesc: "Welcome to the Anaesthesia department at Carmel Hospital.\n\nOur highly skilled team of anaesthesiologists and anaesthesia technicians are dedicated to providing safe and effective care to our patients.\n\nWe understand that surgery and other procedures can be stressful for patients, which is why we strive to make the anaesthesia process as comfortable and stress-free as possible. Our team uses the latest technologies and techniques to provide a wide range of anaesthesia services, from general anaesthesia to regional anaesthesia and conscious sedation.\n\nOur anaesthesiologists work closely with other healthcare professionals to create a customized anaesthesia plan for each patient, taking into consideration their medical history, medications, and other factors. Our team is dedicated to ensuring that our patients are comfortable and safe throughout their procedure.\n\nAt Carmel Hospital’s Anaesthesia department, we prioritize patient safety and follow strict safety protocols and guidelines. We utilize the latest monitoring technologies to ensure that our patients are closely monitored during their procedure, and our team is trained to quickly respond to any complications or emergencies that may arise.\n\nWe are committed to providing exceptional care and service to our patients. Thank you for considering Carmel Hospital’s Anaesthesia department for your healthcare needs.\n\nDepartment details\n\nCategories:\n\nCLINICAL DEPARTMENTS",
    category: "support",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "blood-bank",
    slug: "blood-bank",
    name: "Blood Bank",
    icon: Droplets,
    desc: "Home / Blood Bank",
    fullDesc: "Welcome to the Blood Bank at Carmel Hospital! Our Blood Bank is a critical part of our healthcare system, providing safe and timely blood products to our patients in need.\n\nOur team of experienced and highly trained professionals works tirelessly to ensure that our blood supply is safe, adequate, and readily available to meet the needs of our patients. We follow strict protocols and standards to ensure the safety of our blood products, from the collection and testing of blood to the distribution and administration of blood products.\n\nAt Carmel Hospital’s Blood Bank, we provide a wide range of blood products, including whole blood, red blood cells, platelets, and plasma. We also offer specialized blood products for patients with unique needs, such as rare blood types, neonatal and pediatric patients, and patients with immune deficiencies.\n\nOur team is committed to providing exceptional service and care to our patients. We understand the critical nature of our work and take pride in providing high-quality blood products to our patients in need. We work closely with other healthcare professionals to ensure that our patients receive the best possible care and outcomes.\n\nAt Carmel Hospital’s Blood Bank, we are dedicated to the safety and wellbeing of our patients. We follow the highest standards of safety and adhere to strict regulations and protocols to ensure the quality and safety of our blood products. Thank you for considering our Blood Bank for your healthcare needs.\n\nDepartment Details\n\nCategories:\n\nPARAMEDICAL DEPARTMENTS",
    category: "diagnostic",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "cardiac-care-unit-ccu",
    slug: "cardiac-care-unit-ccu",
    name: "Cardiac Care Unit (CCU)",
    icon: Activity,
    desc: "Welcome to Carmel Hospital’s Cardiac Care Unit (CCU)! Our team of cardiac specialists is dedicated to providing expert and compassionate care to patients with heart conditions. We understand that cardiac care requires specialized knowledge and expertise, and we are committed to providing the highest quality of care to each patient.",
    fullDesc: "Our CCU is equipped with state-of-the-art technology and resources to provide a full range of cardiac care services, including monitoring, diagnosis, and treatment of complex heart conditions. Our team includes cardiologists, nurses, and other specialists who work together to provide comprehensive care to our patients.\n\nAt Carmel Hospital’s CCU, we understand that the wellbeing of our patients’ families and loved ones is just as important as the wellbeing of our patients. That’s why we offer support and resources to families and loved ones of our patients, including education on cardiac care, updates on their loved one’s condition, and emotional support.\n\nWe know that being in the CCU can be a difficult and stressful experience, which is why we strive to create a calm and supportive environment for our patients and their families. Our team is committed to providing personalized care and support to each patient and their family throughout their time in the CCU.\n\nThank you for choosing Carmel Hospital’s CCU for your cardiac care needs. We are dedicated to providing expert and compassionate care to our patients, and we are committed to helping them achieve the best possible outcome.\n\nDepartment details\n\nCategories:\n\nINTENSIVE CARE UNITS",
    category: "speciality",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "cardiology",
    slug: "cardiology",
    name: "Cardiology",
    icon: HeartPulse,
    desc: "Home / Cardiology",
    fullDesc: "Welcome to the Cardiology department at Carmel Hospital. Our team of experienced cardiologists, nurses, and healthcare professionals are dedicated to providing comprehensive and personalized care to patients with heart-related conditions.\n\nOur cardiologists have extensive training and experience in diagnosing and treating a variety of heart-related conditions, including coronary artery disease, arrhythmias, heart failure, and valvular heart disease. We utilize the latest technologies and techniques to provide a wide range of services, including diagnostic testing, medical management, and interventional procedures.\n\nAt Carmel Hospital’s Cardiology department, we offer advanced imaging and diagnostic testing, including echocardiography, stress testing, and cardiac catheterization. We also offer a range of minimally invasive procedures, including angioplasty, stenting, and pacemaker implantation.\n\nWe understand that living with a heart condition can be challenging, which is why our team provides a supportive and compassionate environment for our patients. We prioritize open communication with our patients to ensure they understand their condition, treatment options, and what to expect throughout their care.\n\nOur team is dedicated to providing exceptional care and service to our patients. Thank you for considering Carmel Hospital’s Cardiology department for your healthcare needs.\n\nDepartment details\n\nCategories:\n\nCLINICAL DEPARTMENTS",
    category: "speciality",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "clinical-laboratory",
    slug: "clinical-laboratory",
    name: "Clinical Laboratory",
    icon: Microscope,
    desc: "Welcome to the Clinical Laboratory at Carmel Hospital! Our laboratory is staffed with highly trained and experienced technicians and technologists who are committed to providing accurate and timely diagnostic test results. We understand that laboratory testing plays a critical role in the diagnosis and treatment of medical conditions, and we are dedicated to providing the highest quality of care to our patients.",
    fullDesc: "Our laboratory is equipped with state-of-the-art technology and resources to provide a full range of diagnostic tests, including blood tests, urine tests, and other specialized tests. We use the latest techniques and methodologies to ensure the accuracy and reliability of our test results.\n\nAt Carmel Hospital’s Clinical Laboratory, we understand the importance of timely and accurate test results. That’s why we offer fast turnaround times for our diagnostic tests, so that patients and their healthcare providers can make informed decisions about their care.\n\nWe also understand that laboratory testing can be a stressful experience for some patients, which is why our laboratory staff is committed to providing a comfortable and supportive environment for our patients. Our team is available to answer questions and provide support throughout the testing process.\n\nThank you for choosing Carmel Hospital’s Clinical Laboratory for your diagnostic testing needs. We are dedicated to providing accurate and reliable test results to our patients, and we are committed to helping you achieve the best possible health outcomes.\n\nDepartment details\n\nCategories:\n\nPARAMEDICAL DEPARTMENTS",
    category: "diagnostic",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "clinical-psychology",
    slug: "clinical-psychology",
    name: "Clinical Psychology",
    icon: Brain,
    desc: "Home / Clinical Psychology",
    fullDesc: "Welcome to the Clinical Psychology department at Carmel Hospital. Our team of highly trained clinical psychologists is committed to providing compassionate and evidence-based psychological care to patients of all ages.\n\nWe understand that mental health concerns can impact a person’s overall well-being and quality of life, which is why we strive to create a safe and supportive environment for our patients. Our team works collaboratively with each patient to identify and address their unique mental health concerns and goals.\n\nAt Carmel Hospital’s Clinical Psychology department, we offer a range of psychological services, including individual therapy, couples therapy, family therapy, and group therapy. Our team utilizes a variety of evidence-based treatments, including cognitive-behavioral therapy (CBT), dialectical behavior therapy (DBT), and acceptance and commitment therapy (ACT).\n\nOur clinical psychologists have expertise in treating a wide range of mental health concerns, including anxiety, depression, trauma-related disorders, personality disorders, and more. We also offer psychological assessments and evaluations to assist with diagnosis and treatment planning.\n\nAt Carmel Hospital, we are committed to providing our patients with high-quality care that is tailored to their unique needs. We understand that seeking psychological care can be difficult, which is why we strive to provide a supportive and non-judgmental environment for our patients.\n\nThank you for considering Carmel Hospital’s Clinical Psychology department for your mental health needs. We are dedicated to helping you achieve optimal mental wellness and look forward to working with you.\n\nDepartment details\n\nCategories:\n\nCLINICAL DEPARTMENTS",
    category: "speciality",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "dental",
    slug: "dental",
    name: "Dental",
    icon: Smile,
    desc: "Home / Dental",
    fullDesc: "Welcome to the Dental department at Carmel Hospital, where we are committed to providing top-quality dental care to our patients. Our team of highly skilled dentists and support staff are dedicated to ensuring that you receive personalized and compassionate care for all of your dental needs.\n\nWe understand that maintaining good oral health is important for overall health and well-being. That’s why our dental department offers a comprehensive range of services to meet the unique needs of our patients. Our services include preventative care such as cleanings and checkups, restorative care such as fillings and crowns, and cosmetic procedures such as teeth whitening and veneers.\n\nOur team utilizes the latest technologies and techniques to ensure that our patients receive the best possible care. We also take the time to educate our patients about proper oral hygiene practices and answer any questions they may have about their treatment options.\n\nWhether you are experiencing a toothache or are due for a routine checkup, our dental department is here to provide you with the care and support you need. We are committed to making your dental experience as comfortable and stress-free as possible.\n\nThank you for considering Carmel Hospital’s Dental department for your oral health needs. We look forward to working with you to achieve a healthy and beautiful smile.\n\nDepartment details\n\nCategories:\n\nCLINICAL DEPARTMENTS",
    category: "speciality",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "dermatology",
    slug: "dermatology",
    name: "Dermatology",
    icon: Smile,
    desc: "Home / Dermatology",
    fullDesc: "Welcome to the Dermatology department at Carmel Hospital, where our team of experienced dermatologists is committed to providing high-quality care for all of your skin-related concerns. We understand that skin health is an essential aspect of overall well-being and aim to provide comprehensive and personalized care to our patients.\n\nOur Dermatology department offers a wide range of services, including the diagnosis and treatment of common skin conditions such as acne, eczema, psoriasis, and rosacea. We also provide specialized care for more complex skin conditions like skin cancer, autoimmune skin diseases, and rare skin disorders.\n\nOur team of dermatologists is skilled in the latest treatment methods, including laser therapy, cryotherapy, and photodynamic therapy. We also offer cosmetic treatments such as Botox injections, dermal fillers, and chemical peels to enhance the appearance of your skin.\n\nAt Carmel Hospital’s Dermatology department, we are committed to providing our patients with compassionate and personalized care. We take the time to listen to your concerns, answer your questions, and work with you to develop a treatment plan that meets your unique needs.\n\nIf you are experiencing a skin-related issue, or are interested in cosmetic treatments to improve the appearance of your skin, please don’t hesitate to schedule an appointment with us. Our team is here to help you achieve healthy, beautiful skin.\n\nDepartment details\n\nCategories:\n\nCLINICAL DEPARTMENTS",
    category: "speciality",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "emergency-medicine",
    slug: "emergency-medicine",
    name: "Emergency Medicine",
    icon: ShieldAlert,
    desc: "Home / Emergency Medicine",
    fullDesc: "Welcome to Carmel Hospital’s Emergency Medicine Department! Our team of highly trained emergency physicians, nurses, and staff are dedicated to providing prompt and compassionate care to patients in emergency situations. We understand that medical emergencies can be stressful and overwhelming, and we are here to provide expert care and support when you need it most.\n\nOur Emergency Medicine Department is equipped with state-of-the-art technology and resources to provide a range of emergency services, including evaluation and treatment of acute injuries, illnesses, and medical conditions. Our team is experienced in managing a wide range of emergency situations, from minor injuries to life-threatening conditions.\n\nAt Carmel Hospital’s Emergency Medicine Department, we pride ourselves on our quick response times and our ability to provide expert medical care in a timely and efficient manner. Our team works tirelessly to ensure that our patients receive the best possible care, from the moment they arrive in the emergency room to their follow-up care and recovery.\n\nWe understand that emergencies can happen at any time, which is why our Emergency Medicine Department is open 24 hours a day, seven days a week. Our team is always available to provide expert care and support, no matter what time of day or night it is.\n\nThank you for choosing Carmel Hospital’s Emergency Medicine Department for your emergency medical needs. We are dedicated to providing prompt, compassionate, and expert care to our patients in their time of need.\n\nDepartment Details\n\nCategories:\n\nCLINICAL DEPARTMENTS",
    category: "emergency",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "ent-ear-nose-and-throat",
    slug: "ent-ear-nose-and-throat",
    name: "ENT (Ear, Nose, and Throat)",
    icon: Ear,
    desc: "ENT (Ear, Nose, and Throat) department",
    fullDesc: "Carmel Hospital’s ENT (Ear, Nose, and Throat) department provides comprehensive care for patients with disorders of the ear, nose, throat, and related structures of the head and neck. Our team of experienced physicians and healthcare professionals is committed to providing the highest quality care to our patients.\n\nOur ENT specialists have extensive training and expertise in the diagnosis and treatment of a wide range of conditions, from common ear infections and allergies to more complex conditions such as hearing loss, voice disorders, and sleep apnea. We utilize the latest diagnostic tools and treatments to provide the most effective care possible.\n\nOur services include surgical and non-surgical treatments for both adults and children. We offer minimally invasive procedures that can reduce the need for traditional surgery, resulting in faster recovery times and less discomfort for our patients.\n\nAt Carmel Hospital’s ENT department, we take a patient-centered approach to healthcare. We understand that each patient’s needs are unique, and we work closely with our patients to develop personalized treatment plans that are tailored to their specific needs.\n\nOur state-of-the-art facilities are equipped with the latest technology to ensure that our patients receive the best possible care. We use cutting-edge imaging tools to diagnose and treat conditions with greater accuracy and precision.\n\nWe understand that living with ENT conditions can be challenging, which is why we strive to provide compassionate and supportive care to all of our patients. Our team of healthcare professionals is dedicated to helping our patients achieve optimal health and well-being.\n\nIf you are looking for expert care for an ear, nose, or throat condition, we invite you to visit Carmel Hospital’s ENT department. Our team of specialists is here to provide you with the best possible care and help you achieve a better quality of life.\n\nDepartment Details\n\nCategories:\n\nCLINICAL DEPARTMENTS",
    category: "speciality",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "general-medicine",
    slug: "general-medicine",
    name: "General Medicine",
    icon: Thermometer,
    desc: "General Medicine department",
    fullDesc: "Our team of experienced and highly skilled physicians and staff are dedicated to providing the highest quality medical care to our patients.\n\nAt Carmel Hospital’s General Medicine department, we offer a wide range of services to meet the diverse needs of our patients. Our physicians are experts in the diagnosis, treatment, and management of a variety of acute and chronic medical conditions, including but not limited to:\n\nRespiratory infections and illnesses\n\nDigestive disorders\n\nHypertension and heart disease\n\nDiabetes and other endocrine disorders\n\nInfectious diseases\n\nNeurological disorders\n\nBlood disorders\n\nKidney and urinary tract disorders\n\nRheumatologic and autoimmune disorders\n\nOur team of physicians works collaboratively to provide personalized care that is tailored to the unique needs of each patient. We take a holistic approach to medicine, taking into account not only the physical symptoms but also the emotional and mental well-being of our patients.\n\nWe are committed to providing our patients with the latest medical treatments and technologies to ensure that they receive the best possible care. Our department is equipped with state-of-the-art diagnostic and treatment equipment, and our physicians are trained in the latest medical procedures and techniques.\n\nAt Carmel Hospital’s General Medicine department, we strive to create a comfortable and welcoming environment for our patients. Our staff is friendly and caring, and we are dedicated to providing our patients with the highest level of care and attention.\n\nIf you are in need of medical care, we invite you to visit Carmel Hospital’s General Medicine department. Our team of experts is here to help you achieve optimal health and well-being.\n\nDepartment Details\n\nCategories:\n\nCLINICAL DEPARTMENTS",
    category: "speciality",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "general-surgery",
    slug: "general-surgery",
    name: "General Surgery",
    icon: Syringe,
    desc: "General Surgery department",
    fullDesc: "Welcome to the General Surgery department at Carmel Hospital. Our team of experienced general surgeons and healthcare professionals are dedicated to providing high-quality surgical care to our patients.\n\nOur general surgeons have extensive training and experience in performing a wide range of surgical procedures, including laparoscopic and minimally invasive surgeries. We utilize the latest technologies and techniques to ensure that our patients receive safe, effective, and timely care.\n\nAt Carmel Hospital’s General Surgery department, we treat a variety of conditions, including appendicitis, gallstones, hernias, and cancers of the digestive system. We also provide emergency surgical services for patients in critical condition.\n\nWe understand that undergoing surgery can be a stressful and uncertain time for patients and their families, which is why we prioritize open communication with our patients to ensure they understand their condition, treatment options, and what to expect throughout their surgical experience.\n\nOur team is dedicated to providing exceptional care and service to our patients, and we are committed to ensuring that our patients have a comfortable and positive experience during their time with us. Thank you for considering Carmel Hospital’s General Surgery department for your healthcare needs.\n\nDepartment details\n\nCategories:\n\nCLINICAL DEPARTMENTS",
    category: "speciality",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "gynaecology",
    slug: "gynaecology",
    name: "Gynaecology",
    icon: Cross,
    desc: "Gynaecology Department",
    fullDesc: "Welcome to Carmel Hospital’s Gynaecology Department! Our team of highly trained and experienced gynecologists is dedicated to providing compassionate and comprehensive care to women of all ages. We understand that women’s health is complex and unique, and we strive to meet the individual needs of each patient.\n\nOur gynecologists offer a full range of services, including routine gynecologic exams, family planning and contraception, prenatal care, menopause management, and treatment for gynecologic disorders. We also specialize in minimally invasive gynecologic surgery, including laparoscopic and robotic-assisted procedures.\n\nAt Carmel Hospital’s Gynaecology Department, we understand the importance of preventative care. We encourage our patients to schedule regular exams to detect and prevent gynecologic issues before they become serious. Our gynecologists also take the time to educate patients on the importance of self-care and healthy lifestyle choices.\n\nWe know that visiting a hospital can be stressful, which is why we strive to create a warm and welcoming environment for our patients. Our staff is committed to providing personalized care and support throughout each patient’s journey.\n\nAt Carmel Hospital’s Gynaecology Department, we are dedicated to empowering women to take charge of their health and wellness. Thank you for choosing us for your gynecologic care needs. We look forward to helping you achieve optimal health and wellbeing.\n\nDepartment Details\n\nCategories:\n\nCLINICAL DEPARTMENTS",
    category: "speciality",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "laparoscopic-surgery",
    slug: "laparoscopic-surgery",
    name: "Laparoscopic Surgery",
    icon: Scan,
    desc: "Laparoscopic Surgery Department",
    fullDesc: "Welcome to Carmel Hospital’s Laparoscopic Surgery Department! Our team of skilled surgeons is dedicated to providing minimally invasive surgical options to our patients. We understand that surgery can be a stressful and scary experience, which is why we offer laparoscopic surgery as an alternative to traditional open surgery.\n\nLaparoscopic surgery is a minimally invasive procedure that involves small incisions and the use of specialized surgical instruments and cameras to access and treat the affected area. This technique results in less pain, scarring, and a shorter recovery time for our patients.\n\nOur laparoscopic surgeons are trained in a range of procedures, including gallbladder removal, hernia repair, appendectomy, and hysterectomy. We use the latest technologies and techniques to ensure that our patients receive the best possible care.\n\nAt Carmel Hospital’s Laparoscopic Surgery Department, we understand that each patient’s needs are unique. We work closely with our patients to develop individualized treatment plans that meet their specific needs and goals. Our team also takes the time to educate patients on the procedure, the recovery process, and any potential risks or complications.\n\nWe know that surgery can be a daunting experience, which is why we strive to create a supportive and comfortable environment for our patients. Our staff is dedicated to providing personalized care and support throughout each patient’s surgical journey.\n\nThank you for choosing Carmel Hospital’s Laparoscopic Surgery Department for your surgical needs. We look forward to helping you achieve optimal health and wellbeing with our minimally invasive surgical options.\n\nDepartment Details\n\nCategories:\n\nCLINICAL DEPARTMENTS",
    category: "speciality",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "medical-intensive-care-unit-micu",
    slug: "medical-intensive-care-unit-micu",
    name: "Medical Intensive Care Unit (MICU)",
    icon: Activity,
    desc: "Welcome to Carmel Hospital’s Medical Intensive Care Unit (MICU)! Our team of highly skilled and experienced healthcare professionals is dedicated to providing compassionate and advanced care to critically ill patients. We understand that patients in the MICU require specialized care and attention, and we are committed to providing the highest quality of care to each patient.",
    fullDesc: "Our MICU is equipped with state-of-the-art technology and resources to provide a full range of critical care services, including monitoring, diagnosis, and treatment of complex medical conditions. Our team of experts includes intensivists, nurses, respiratory therapists, and other specialists who work together to provide comprehensive care to our patients.\n\nAt Carmel Hospital’s MICU, we understand that the wellbeing of our patients’ families and loved ones is just as important as the wellbeing of our patients. That’s why we offer support and resources to families and loved ones of our patients, including education on critical care, updates on their loved one’s condition, and emotional support.\n\nWe know that being in the MICU can be a difficult and stressful experience, which is why we strive to create a calm and supportive environment for our patients and their families. Our team is committed to providing personalized care and support to each patient and their family throughout their time in the MICU.\n\nThank you for choosing Carmel Hospital’s MICU for your critical care needs. We are dedicated to providing advanced and compassionate care to our patients, and we are committed to helping them achieve the best possible outcome.\n\nDepartment details\n\nCategories:\n\nINTENSIVE CARE UNITS",
    category: "speciality",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "neonatal-intensive-care-unit-nicu",
    slug: "neonatal-intensive-care-unit-nicu",
    name: "Neonatal Intensive Care Unit (NICU)",
    icon: Baby,
    desc: "Welcome to Carmel Hospital’s Neonatal Intensive Care Unit (NICU)! Our team of neonatal specialists is dedicated to providing expert and compassionate care to premature and critically ill newborns. We understand that caring for premature and critically ill newborns requires specialized knowledge and expertise, and we are committed to providing the highest quality of care to each baby.",
    fullDesc: "Our NICU is equipped with state-of-the-art technology and resources to provide a full range of neonatal care services, including monitoring, diagnosis, and treatment of complex medical conditions. Our team includes neonatologists, nurses, respiratory therapists, and other specialists who work together to provide comprehensive care to our patients.\n\nAt Carmel Hospital’s NICU, we understand that the wellbeing of our patients’ families and loved ones is just as important as the wellbeing of our patients. That’s why we offer support and resources to families and loved ones of our patients, including education on neonatal care, updates on their baby’s condition, and emotional support.\n\nWe know that having a premature or critically ill newborn in the NICU can be a difficult and stressful experience, which is why we strive to create a calm and supportive environment for our patients and their families. Our team is committed to providing personalized care and support to each baby and their family throughout their time in the NICU.\n\nThank you for choosing Carmel Hospital’s NICU for your newborn’s care needs. We are dedicated to providing expert and compassionate care to our patients, and we are committed to helping them achieve the best possible outcome.\n\nDepartment details\n\nCategories:\n\nINTENSIVE CARE UNITS",
    category: "speciality",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "nephrology",
    slug: "nephrology",
    name: "Nephrology",
    icon: Stethoscope,
    desc: "Nephrology & Dialysis",
    fullDesc: "Home / Nephrology & Dialysis\n\nDialysis\n\nWelcome to the Nephrology & Dialysis department at Carmel Hospital. Our team of experienced nephrologists, nurses, and healthcare professionals are dedicated to providing comprehensive and personalized care to patients with kidney disease.\n\nOur nephrologists have extensive training and experience in diagnosing and treating a variety of kidney-related conditions, including chronic kidney disease, glomerulonephritis, and renal failure. We utilize the latest technologies and techniques to provide a wide range of services, including diagnostic testing, medical management, and dialysis.\n\nAt Carmel Hospital’s Nephrology & Dialysis department, we offer both inpatient and outpatient dialysis services for patients with end-stage renal disease. We use advanced equipment and techniques to ensure that our patients receive safe and effective treatment.\n\nWe understand that living with kidney disease can be challenging, which is why our team provides a supportive and compassionate environment for our patients. We prioritize open communication with our patients to ensure they understand their condition, treatment options, and what to expect throughout their care.\n\nOur team is dedicated to providing exceptional care and service to our patients. Thank you for considering Carmel Hospital’s Nephrology & Dialysis department for your healthcare needs.\n\nDepartment details\n\nCategories:\n\nCLINICAL DEPARTMENTS",
    category: "speciality",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "ophthalmology",
    slug: "ophthalmology",
    name: "Ophthalmology",
    icon: Eye,
    desc: "Ophthalmology Department",
    fullDesc: "Welcome to Carmel Hospital’s Ophthalmology Department! Our team of expert ophthalmologists is dedicated to providing the highest quality of eye care to our patients. We understand that vision is an essential part of our lives, and we strive to help our patients maintain healthy eyesight.\n\nOur ophthalmologists are skilled in diagnosing and treating a range of eye conditions, from simple refractive errors to complex disorders. We use the latest technologies and techniques to ensure that our patients receive the best possible care.\n\nOur services include routine eye exams, cataract surgery, glaucoma management, corneal transplants, and treatment for retinal diseases. We also offer LASIK and other refractive surgeries to help patients reduce their dependence on glasses and contact lenses.\n\nAt Carmel Hospital’s Ophthalmology Department, we believe that patient education is essential. Our ophthalmologists take the time to explain each patient’s condition and treatment options in detail. We work closely with our patients to develop individualized treatment plans that meet their specific needs and goals.\n\nWe understand that visiting a hospital can be stressful, which is why we strive to create a comfortable and welcoming environment for our patients. Our friendly staff is always available to answer questions and provide support.\n\nThank you for choosing Carmel Hospital’s Ophthalmology Department for your eye care needs. We look forward to helping you achieve optimal eye health and vision.\n\nDepartment Details\n\nCategories:\n\nCLINICAL DEPARTMENTS",
    category: "speciality",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "orthopaedics",
    slug: "orthopaedics",
    name: "Orthopaedics",
    icon: Bone,
    desc: "Orthopaedics department",
    fullDesc: "Carmel Hospital’s Orthopaedics department is dedicated to providing exceptional care for patients with musculoskeletal conditions, injuries, and disorders. Our team of experienced orthopaedic surgeons and healthcare professionals are committed to providing the highest quality care to our patients.\n\nWe understand that musculoskeletal conditions can be painful and debilitating, and we offer a wide range of services to help patients achieve optimal health and mobility. Our services include surgical and non-surgical treatments for a variety of conditions, including fractures, arthritis, joint pain, sports injuries, and more.\n\nAt Carmel Hospital’s Orthopaedics department, we use the latest diagnostic tools and imaging technology to ensure accurate diagnoses and effective treatment plans. Our team of experts utilizes advanced surgical techniques to minimize pain, scarring, and recovery time.\n\nWe take a patient-centered approach to healthcare and understand that each patient’s needs are unique. We work closely with our patients to develop personalized treatment plans that are tailored to their specific needs and goals.\n\nOur facilities are state-of-the-art, with the latest technology and equipment to ensure that our patients receive the best possible care. We offer a comprehensive range of services, including physical therapy, rehabilitation, and pain management, to help our patients achieve optimal health and well-being.\n\nAt Carmel Hospital’s Orthopaedics department, we are committed to providing compassionate and supportive care to all of our patients. We believe that a positive patient experience is just as important as clinical expertise, and we strive to make each patient feel comfortable and cared for throughout their journey to recovery.\n\nIf you are seeking expert care for a musculoskeletal condition, we invite you to visit Carmel Hospital’s Orthopaedics department. Our team of specialists is here to provide you with the best possible care and help you achieve a better quality of life.\n\nDepartment Details\n\nCategories:\n\nCLINICAL DEPARTMENTS",
    category: "speciality",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "pediatric-intensive-care-unit-picu",
    slug: "pediatric-intensive-care-unit-picu",
    name: "Pediatric Intensive Care Unit (PICU)",
    icon: Baby,
    desc: "Welcome to Carmel Hospital’s Pediatric Intensive Care Unit (PICU)! Our team of pediatric specialists is dedicated to providing expert and compassionate care to critically ill children. We understand that the care of sick children requires specialized knowledge and expertise, and we are committed to providing the highest quality of care to each child.",
    fullDesc: "Our PICU is equipped with state-of-the-art technology and resources to provide a full range of critical care services, including monitoring, diagnosis, and treatment of complex medical conditions. Our team includes pediatric intensivists, nurses, respiratory therapists, and other specialists who work together to provide comprehensive care to our patients.\n\nAt Carmel Hospital’s PICU, we understand that the wellbeing of our patients’ families and loved ones is just as important as the wellbeing of our patients. That’s why we offer support and resources to families and loved ones of our patients, including education on critical care, updates on their child’s condition, and emotional support.\n\nWe know that being in the PICU can be a difficult and stressful experience, which is why we strive to create a calm and supportive environment for our patients and their families. Our team is committed to providing personalized care and support to each child and their family throughout their time in the PICU.\n\nThank you for choosing Carmel Hospital’s PICU for your child’s critical care needs. We are dedicated to providing expert and compassionate care to our patients, and we are committed to helping them achieve the best possible outcome.\n\nDepartment details\n\nCategories:\n\nINTENSIVE CARE UNITS",
    category: "speciality",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "pediatrics",
    slug: "pediatrics",
    name: "Pediatrics",
    icon: Baby,
    desc: "Pediatrics department",
    fullDesc: "Our Pediatrics department at Carmel Hospital provides high-quality healthcare services to children of all ages, from infants to adolescents. Our team of experienced and compassionate pediatricians and healthcare professionals are dedicated to delivering the best possible care.\n\nWe understand that children have unique healthcare needs, and we strive to provide personalized and family-centered care. Our services include routine check-ups, vaccinations, sick visits, and management of chronic conditions. Our physicians are experts in diagnosing and treating common childhood illnesses such as colds, flu, asthma, and ear infections. We also provide specialized care for children with complex medical needs, including developmental delays and behavioral issues.\n\nAt Carmel Hospital’s Pediatrics department, we believe in a holistic approach to healthcare that emphasizes prevention and education. We provide parents with the necessary resources and tools to help their children stay healthy and thrive.\n\nWe understand that visiting the hospital can be stressful for children and their families. Our team of professionals is specially trained to work with children of all ages, and we strive to create a warm and welcoming environment that is designed to make our young patients feel safe and comfortable.\n\nIf you are looking for a pediatrician or need medical care for your child, we invite you to visit our Pediatrics department at Carmel Hospital. Our team of experts is here to help your child grow and develop into a happy and healthy adult.\n\nDepartment Details\n\nCategories:\n\nCLINICAL DEPARTMENTS",
    category: "speciality",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "pharmacy",
    slug: "pharmacy",
    name: "Pharmacy",
    icon: Pill,
    desc: "Home / Pharmacy",
    fullDesc: "Welcome to the Pharmacy at Carmel Hospital! Our Pharmacy is an integral part of the healthcare team, providing safe and effective medication management to our patients.\n\nOur team of experienced pharmacists and pharmacy technicians work diligently to ensure that our patients receive the appropriate medications and dosage regimens for their medical conditions. We work closely with other healthcare professionals to ensure that our patients receive the best possible outcomes from their medications.\n\nAt Carmel Hospital’s Pharmacy, we provide a wide range of medications, from over-the-counter medications to prescription medications. We also offer specialized medications for patients with unique needs, such as chemotherapy drugs, immunosuppressants, and medications for chronic conditions.\n\nOur team is committed to providing exceptional service and care to our patients. We understand the importance of medication safety and take great care to ensure that our medications are dispensed accurately and appropriately. We also provide patient education and counseling to ensure that our patients understand how to take their medications and what to expect from their treatment.\n\nAt Carmel Hospital’s Pharmacy, we are dedicated to the safety and wellbeing of our patients. We adhere to the highest standards of safety and follow strict regulations and protocols to ensure that our medications are safe and effective. Thank you for considering our Pharmacy for your healthcare needs.\n\nDepartment details\n\nCategories:\n\nPARAMEDICAL DEPARTMENTS",
    category: "diagnostic",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "physiotherapy",
    slug: "physiotherapy",
    name: "Physiotherapy",
    icon: Activity,
    desc: "Home / Physiotherapy",
    fullDesc: "Welcome to the Physiotherapy department at Carmel Hospital! Our team of experienced and licensed physiotherapists is dedicated to helping our patients recover from injuries and illnesses, improve their mobility, and regain their strength and independence.\n\nAt Carmel Hospital’s Physiotherapy department, we offer a wide range of services to meet the unique needs of each of our patients. Our team works closely with patients, their families, and other healthcare professionals to develop personalized treatment plans that address their specific goals and needs.\n\nOur services include manual therapy, exercise therapy, electrotherapy, and various specialized treatments such as hydrotherapy, vestibular rehabilitation, and more. We also offer education and training on proper posture, body mechanics, and injury prevention.\n\nOur team is committed to providing high-quality care and helping our patients achieve the best possible outcomes. We use the latest techniques and technologies to help our patients regain their mobility, strength, and function. Our goal is to help our patients achieve their goals and return to their daily activities as quickly and safely as possible.\n\nAt Carmel Hospital’s Physiotherapy department, we are dedicated to providing compassionate care and exceptional service to our patients. We understand the importance of restoring our patients’ quality of life and work tirelessly to help them achieve their goals. Thank you for considering our Physiotherapy department for your healthcare needs.\n\nDepartment details\n\nCategories:\n\nPARAMEDICAL DEPARTMENTS",
    category: "support",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "psychiatry",
    slug: "psychiatry",
    name: "Psychiatry",
    icon: Brain,
    desc: "Home / Psychiatry",
    fullDesc: "Welcome to the Psychiatry department at Carmel Hospital. Our team of experienced psychiatrists, psychologists, social workers, and therapists are dedicated to providing comprehensive and personalized care to patients with mental health conditions.\n\nWe understand that mental health is just as important as physical health, and we are committed to providing our patients with the support they need to achieve optimal mental wellness. Our team utilizes evidence-based treatments and therapies to address a wide range of mental health conditions, including depression, anxiety, bipolar disorder, schizophrenia, and substance abuse disorders.\n\nAt Carmel Hospital’s Psychiatry department, we offer a variety of services, including psychiatric evaluations, individual and group therapy, medication management, and addiction treatment programs. Our team works closely with each patient to develop an individualized treatment plan that addresses their unique needs and goals.\n\nWe understand that seeking help for mental health issues can be challenging, which is why our team provides a supportive and non-judgmental environment for our patients. We prioritize open communication with our patients to ensure they feel heard and understood throughout their care.\n\nOur team is dedicated to providing exceptional care and service to our patients. Thank you for considering Carmel Hospital’s Psychiatry department for your mental health needs.\n\nDepartment details\n\nCategories:\n\nCLINICAL DEPARTMENTS",
    category: "speciality",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "radiology",
    slug: "radiology",
    name: "Radiology",
    icon: Microscope,
    desc: "Home / Radiology",
    fullDesc: "Welcome to the Radiology department at Carmel Hospital! Our team of experienced radiologists and imaging technologists is dedicated to providing high-quality diagnostic and interventional radiology services to our patients.\n\nAt Carmel Hospital’s Radiology department, we use state-of-the-art imaging technology to provide accurate and timely diagnoses to our patients. Our services include X-ray, ultrasound, CT scan, MRI, PET-CT, and more. We also offer interventional radiology procedures such as biopsy, drainage, and tumor ablation.\n\nOur team works closely with other healthcare professionals to provide coordinated and comprehensive care to our patients. We understand the importance of timely and accurate diagnoses, and we strive to provide the highest level of service to our patients.\n\nIn addition, our department is committed to the safety and comfort of our patients. We adhere to the highest standards of safety and use radiation only when necessary and in the smallest amount possible.\n\nAt Carmel Hospital’s Radiology department, we are dedicated to providing exceptional service and care to our patients. We understand the importance of accurate and timely diagnoses, and we use the latest technology and techniques to provide the best possible outcomes for our patients. Thank you for considering our Radiology department for your healthcare needs.\n\nDepartment Details\n\nCategories:\n\nPARAMEDICAL DEPARTMENTS",
    category: "diagnostic",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
  {
    id: "sicu",
    slug: "sicu",
    name: "SICU",
    icon: Activity,
    desc: "Home / SICU",
    fullDesc: "Intensive Care Units\n\nWelcome to the Surgical Intensive Care Unit (SICU) at Carmel Hospital! Our team of highly skilled and experienced healthcare professionals is dedicated to providing expert and compassionate care to patients who require specialized surgical care. We understand that the SICU plays a critical role in the recovery of surgical patients, and we are committed to providing the best possible care to our patients.\n\nOur SICU is equipped with state-of-the-art technology and resources to provide a full range of surgical care services, including monitoring, diagnosis, and treatment of complex medical conditions. Our team includes surgeons, nurses, respiratory therapists, and other specialists who work together to provide comprehensive care to our patients.\n\nAt Carmel Hospital’s SICU, we understand that surgery can be a stressful experience for patients and their families. That’s why we strive to create a calm and supportive environment for our patients, where they can focus on their recovery. Our team is committed to providing personalized care and support to each patient and their family throughout their time in the SICU.\n\nWe also understand the importance of communication and collaboration between healthcare providers and patients and their families. That’s why we keep our patients and their families informed and involved in their care, and we work closely with healthcare providers to ensure the best possible outcomes for our patients.\n\nThank you for choosing Carmel Hospital’s SICU for your surgical care needs. We are dedicated to providing expert and compassionate care to our patients, and we are committed to helping them achieve the best possible recovery.\n\nDepartment details\n\nCategories:\n\nINTENSIVE CARE UNITS",
    category: "speciality",
    image: "/hero_slideshow/eb-website-image-hero-3840x2560.webp",
    procedures: [],
    facilities: [],
  },
];

export function getDepartmentBySlug(slug: string): Department | undefined {
  return departments.find((d) => d.slug === slug);
}

export function getDepartmentsByCategory(category: string): Department[] {
  if (category === "all") return departments;
  return departments.filter((d) => d.category === category);
}
